### ISSUE TITLE
Feature request: tab complete messages

### ISSUE THREAD

**Issue by marioenache** [tritonmc/Triton#386] opened 2024-02-11 18:08 UTC
### Describe the Feature

Hello! As a future enhancement, I will go with tab complete placeholders for Triton plugin. I have attached a screenshot to be more on point about my idea.
![image](https://github.com/tritonmc/Triton/assets/159150268/d325955a-99dc-43fe-9176-7d3bb4cdb9cc)

**Comment by diogotcorreia** [comment] 2024-07-15 13:45
Duplicate of #318, follow that issue for progress

**Closed as not planned by diogotcorreia** 2024-07-15 13:45 UTC
Labels: type:feature, module:bungeecord, module:velocity, module:spigot
