### ISSUE TITLE
Crash triton

### ISSUE THREAD

**Issue by vCren** [tritonmc/Triton#147] opened 2021-04-08 17:37 UTC
Hi, I have a problem with the triton in the console, crash pops up, this one: https://pastebin.com/riUPg5Cz

**Comment by diogotcorreia** [comment] 2021-04-18 22:03
Hi
I can't really figure out what the problem is from that log.
Do you have more logs that you can send me, either through Discord or here? (check if the lines from Triton are below 2000, otherwise they're probably useless)

![image](https://user-images.githubusercontent.com/7467891/115162226-3d5f5e00-a09a-11eb-8d3a-8568a537a3e2.png)

**Comment by diogotcorreia** [comment] 2021-12-19 15:07
I'm closing this because I don't have enough information. Please open a new issue if this happens again with the latest version.

**Closed by diogotcorreia** 2021-12-19 15:07 UTC
Labels: bug, can't reproduce
