### ISSUE TITLE
Translation support for recipe items

### ISSUE THREAD

**Issue by mani1232** [tritonmc/Triton#308] opened 2023-05-22 06:53 UTC
### Describe the Feature

![image](https://github.com/tritonmc/Triton/assets/70480001/606ec2c3-2397-4918-93f1-4d54eeaa822d)

**Comment by diogotcorreia** [comment] 2024-07-15 13:41
Duplicate of #244, follow that issue for progress.

**Closed as not planned by diogotcorreia** 2024-07-15 13:41 UTC
Labels: type:feature, module:spigot
