### ISSUE TITLE
Item does not appear in hand with middle click

### ISSUE THREAD

**Issue by Keynadi** [tritonmc/Triton#121] opened 2020-10-18 15:26 UTC
**Describe the bug**
The item from the inventory does not appear in the hand when the middle mouse button is clicked. Survival mode.

**To Reproduce**
1: Change "allow-in-inventory" to true;
2: Move any block to your inventory in survival mode (just don't hold this block in your hand).
3: Middle click on the same block as you have in your inventory.

**Expected behavior**
The block from the inventory should appear in your hand, but it does not appear.

**Screenshots (optional)**
Video:
https://drive.google.com/file/d/1AGemHNJYovwgFMKV1rZR991Gqi3r_2IS/view?usp=sharing

**Server information (please complete the following information):**
 - Server Minecraft Version: 1.16.1
 - Client Minecraft Version: 1.16.1
 - BungeeCord: No
 - Triton Version: 3.1.4

**Additional context**
Looks like after changing "allow-in-inventory" to true from false and reloading triton in the first middle mouse click all goes as needed (item appears in hand) but after that, it does not appear.

**Comment by diogotcorreia** [comment] 2020-10-26 08:53
This was caused by ProtocolLib editing item NBT data when reading it. Using their other method `NbtFactory#fromItemOptional` fixes the issue.
The fix will be included in the 3.1.5.

**Closed** 2020-10-26 08:56 UTC
Labels: bug
