### ISSUE TITLE
java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by AfkF24** [tritonmc/Triton#103] opened 2020-04-28 21:34 UTC
`java.util.ConcurrentModificationException: null` on join:
```
[23:33:41 WARN]: [Triton] Task #5366093 for Triton v2.6.4 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_201]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_201]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_201]
        at com.rexcantor64.triton.h.d.b(ProtocolLibListener.java:787) ~[?:?]
        at com.rexcantor64.triton.j.d.refreshAll(SpigotLanguagePlayer.java:2124) ~[?:?]
        at com.rexcantor64.triton.j.d.a(SpigotLanguagePlayer.java:68) ~[?:?]
        at com.rexcantor64.triton.j.d.setLang(SpigotLanguagePlayer.java:51) ~[?:?]
        at com.rexcantor64.triton.h.d.a(ProtocolLibListener.java:728) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-226]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by diogotcorreia** [comment] 2020-08-06 00:00
Duplicate of #102

**Closed by diogotcorreia** 2020-08-06 00:00 UTC
Labels: bug, duplicate
